{
    'name':"My library",
    'summary':'Manage books easily',
    "description":"""Long description""",
    'author':"zhou zhibo",
    'website':'http://www.example.com',
    'category':'Uncategorized',
    'version':'14.0.1',
    'depends':['base'],
    'data':['views/library_book.xml',
            'views/library_book_categ.xml',
            'views/res_partner.xml',
            'views/parent.xml',
            'views/menu.xml',
            'views/library_book_rent.xml',
            'views/library_rent_wizard.xml',
            'security/groups.xml',
            'security/ir.model.access.csv',],
    'demo':[],
    'auto_install':True,
    'installable':True,
    'application':True,
}